services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nguyenngocnhan1/projectnhan:latest
    container_name: node-api
    ports:
      - "5005:86"
    restart: always
