name: CI/CD - Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t nguyenngocnhan1/projectnhan:latest .
          docker push nguyenngocnhan1/projectnhan:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker pull nguyenngocnhan1/projectnhan:latest
            sudo docker stop projectnhan-app || true
            sudo docker rm projectnhan-app || true
            sudo docker run -d -p 5005:86 --name projectnhan-app nguyenngocnhan1/projectnhan:latest
